//! English Toggle — translate natural language descriptions into Aether (.ae) code.
//!
//! Calls Claude via the Anthropic Messages API using sdk/SYSTEM_PROMPT.md as the
//! system prompt. Requires ANTHROPIC_API_KEY environment variable.

const SYSTEM_PROMPT: &str = include_str!("../sdk/SYSTEM_PROMPT.md");

/// Translate a natural language description into Aether source code.
///
/// Returns the raw `.ae` program text generated by Claude.
/// Requires `ANTHROPIC_API_KEY` to be set in the environment.
pub async fn translate(
    description: &str,
) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
    let api_key = std::env::var("ANTHROPIC_API_KEY")
        .map_err(|_| "ANTHROPIC_API_KEY not set — English Toggle requires Claude API access")?;

    let client = reqwest::Client::new();
    let response = client
        .post("https://api.anthropic.com/v1/messages")
        .header("x-api-key", &api_key)
        .header("anthropic-version", "2023-06-01")
        .header("content-type", "application/json")
        .json(&serde_json::json!({
            "model": "claude-haiku-4-5-20251001",
            "max_tokens": 4096,
            "system": SYSTEM_PROMPT,
            "messages": [{ "role": "user", "content": description }]
        }))
        .send()
        .await
        .map_err(|e| format!("Translation API call failed: {}", e))?;

    let body: serde_json::Value = response
        .json()
        .await
        .map_err(|e| format!("Translation response parse failed: {}", e))?;

    // Check for API-level errors
    if let Some(err) = body.get("error") {
        return Err(format!("Anthropic API error: {}", err).into());
    }

    body["content"][0]["text"]
        .as_str()
        .map(|s| s.trim().to_string())
        .ok_or_else(|| format!("Unexpected API response shape: {}", body).into())
}
